//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrangementChart_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrangementChart_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{urn:eu:taxud:dac6:v1}PersonOrOrganisation_Type"/&gt;
 *         &lt;element name="Ownership" type="{urn:eu:taxud:dac6:v1}Percentage_Type" minOccurs="0"/&gt;
 *         &lt;element name="InvestAmount" type="{urn:eu:taxud:dac6:v1}Amount_Type" minOccurs="0"/&gt;
 *         &lt;element name="OtherInfo" type="{urn:eu:taxud:dac6:v1}StringMin1Max4000WithLang_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ListChilds" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ChildRTP" type="{urn:eu:taxud:dac6:v1}ArrangementChart_Type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrangementChart_Type", propOrder = {
    "id",
    "ownership",
    "investAmount",
    "otherInfo",
    "listChilds"
})
public class ArrangementChartType {

    @XmlElement(name = "ID", required = true)
    protected PersonOrOrganisationType id;
    @XmlElement(name = "Ownership")
    @XmlSchemaType(name = "integer")
    protected Integer ownership;
    @XmlElement(name = "InvestAmount")
    protected AmountType investAmount;
    @XmlElement(name = "OtherInfo")
    protected List<StringMin1Max4000WithLangType> otherInfo;
    @XmlElement(name = "ListChilds")
    protected ArrangementChartType.ListChilds listChilds;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public PersonOrOrganisationType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public void setID(PersonOrOrganisationType value) {
        this.id = value;
    }

    /**
     * Gets the value of the ownership property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOwnership() {
        return ownership;
    }

    /**
     * Sets the value of the ownership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOwnership(Integer value) {
        this.ownership = value;
    }

    /**
     * Gets the value of the investAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getInvestAmount() {
        return investAmount;
    }

    /**
     * Sets the value of the investAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setInvestAmount(AmountType value) {
        this.investAmount = value;
    }

    /**
     * Gets the value of the otherInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringMin1Max4000WithLangType }
     * 
     * 
     */
    public List<StringMin1Max4000WithLangType> getOtherInfo() {
        if (otherInfo == null) {
            otherInfo = new ArrayList<>();
        }
        return this.otherInfo;
    }

    /**
     * Gets the value of the listChilds property.
     * 
     * @return
     *     possible object is
     *     {@link ArrangementChartType.ListChilds }
     *     
     */
    public ArrangementChartType.ListChilds getListChilds() {
        return listChilds;
    }

    /**
     * Sets the value of the listChilds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrangementChartType.ListChilds }
     *     
     */
    public void setListChilds(ArrangementChartType.ListChilds value) {
        this.listChilds = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ChildRTP" type="{urn:eu:taxud:dac6:v1}ArrangementChart_Type" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "childRTP"
    })
    public static class ListChilds {

        @XmlElement(name = "ChildRTP", required = true)
        protected List<ArrangementChartType> childRTP;

        /**
         * Gets the value of the childRTP property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the childRTP property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChildRTP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ArrangementChartType }
         * 
         * 
         */
        public List<ArrangementChartType> getChildRTP() {
            if (childRTP == null) {
                childRTP = new ArrayList<>();
            }
            return this.childRTP;
        }

    }

}
