//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociatedEnterprise_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedEnterprise_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AssociatedEnterpriseID" type="{urn:eu:taxud:dac6:v1}PersonOrOrganisation_Type"/&gt;
 *         &lt;element name="AffectedPerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedEnterprise_Type", propOrder = {
    "associatedEnterpriseID",
    "affectedPerson"
})
public class AssociatedEnterpriseType {

    @XmlElement(name = "AssociatedEnterpriseID", required = true)
    protected PersonOrOrganisationType associatedEnterpriseID;
    @XmlElement(name = "AffectedPerson")
    protected boolean affectedPerson;

    /**
     * Gets the value of the associatedEnterpriseID property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public PersonOrOrganisationType getAssociatedEnterpriseID() {
        return associatedEnterpriseID;
    }

    /**
     * Sets the value of the associatedEnterpriseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public void setAssociatedEnterpriseID(PersonOrOrganisationType value) {
        this.associatedEnterpriseID = value;
    }

    /**
     * Gets the value of the affectedPerson property.
     * 
     */
    public boolean isAffectedPerson() {
        return affectedPerson;
    }

    /**
     * Sets the value of the affectedPerson property.
     * 
     */
    public void setAffectedPerson(boolean value) {
        this.affectedPerson = value;
    }

}
