//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DAC6Disclosure_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DAC6Disclosure_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DisclosureID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="17"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DisclosureVersion" type="{urn:eu:taxud:dac6:v1}DisclosureVersion_EnumType"/&gt;
 *         &lt;element name="Language" type="{urn:eu:taxud:isotypes:v1}LanguageCode_Type" minOccurs="0"/&gt;
 *         &lt;element name="Disclosing" type="{urn:eu:taxud:dac6:v1}Discloser"/&gt;
 *         &lt;element name="InitialDisclosureMA" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="RelevantTaxPayers" type="{urn:eu:taxud:dac6:v1}RelevantTaxpayers_Type" minOccurs="0"/&gt;
 *         &lt;element name="Intermediaries" type="{urn:eu:taxud:dac6:v1}Intermediaries_Type" minOccurs="0"/&gt;
 *         &lt;element name="AffectedPersons" type="{urn:eu:taxud:dac6:v1}AffectedPersons_Type" minOccurs="0"/&gt;
 *         &lt;element name="DisclosureInformation" type="{urn:eu:taxud:dac6:v1}DisclosureInformation_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="GDPRUpdated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DAC6Disclosure_Type", propOrder = {
    "disclosureID",
    "disclosureVersion",
    "language",
    "disclosing",
    "initialDisclosureMA",
    "relevantTaxPayers",
    "intermediaries",
    "affectedPersons",
    "disclosureInformation"
})
public class DAC6DisclosureType {

    @XmlElement(name = "DisclosureID", required = true)
    protected String disclosureID;
    @XmlElement(name = "DisclosureVersion", required = true)
    @XmlSchemaType(name = "string")
    protected DisclosureVersionEnumType disclosureVersion;
    @XmlElement(name = "Language")
    @XmlSchemaType(name = "string")
    protected LanguageCodeType language;
    @XmlElement(name = "Disclosing", required = true)
    protected Discloser disclosing;
    @XmlElement(name = "InitialDisclosureMA", defaultValue = "false")
    protected boolean initialDisclosureMA;
    @XmlElement(name = "RelevantTaxPayers")
    protected RelevantTaxpayersType relevantTaxPayers;
    @XmlElement(name = "Intermediaries")
    protected IntermediariesType intermediaries;
    @XmlElement(name = "AffectedPersons")
    protected AffectedPersonsType affectedPersons;
    @XmlElement(name = "DisclosureInformation")
    protected DisclosureInformationType disclosureInformation;
    @XmlAttribute(name = "GDPRUpdated")
    protected Boolean gdprUpdated;

    /**
     * Gets the value of the disclosureID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosureID() {
        return disclosureID;
    }

    /**
     * Sets the value of the disclosureID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosureID(String value) {
        this.disclosureID = value;
    }

    /**
     * Gets the value of the disclosureVersion property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureVersionEnumType }
     *     
     */
    public DisclosureVersionEnumType getDisclosureVersion() {
        return disclosureVersion;
    }

    /**
     * Sets the value of the disclosureVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureVersionEnumType }
     *     
     */
    public void setDisclosureVersion(DisclosureVersionEnumType value) {
        this.disclosureVersion = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageCodeType }
     *     
     */
    public LanguageCodeType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageCodeType }
     *     
     */
    public void setLanguage(LanguageCodeType value) {
        this.language = value;
    }

    /**
     * Gets the value of the disclosing property.
     * 
     * @return
     *     possible object is
     *     {@link Discloser }
     *     
     */
    public Discloser getDisclosing() {
        return disclosing;
    }

    /**
     * Sets the value of the disclosing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discloser }
     *     
     */
    public void setDisclosing(Discloser value) {
        this.disclosing = value;
    }

    /**
     * Gets the value of the initialDisclosureMA property.
     * 
     */
    public boolean isInitialDisclosureMA() {
        return initialDisclosureMA;
    }

    /**
     * Sets the value of the initialDisclosureMA property.
     * 
     */
    public void setInitialDisclosureMA(boolean value) {
        this.initialDisclosureMA = value;
    }

    /**
     * Gets the value of the relevantTaxPayers property.
     * 
     * @return
     *     possible object is
     *     {@link RelevantTaxpayersType }
     *     
     */
    public RelevantTaxpayersType getRelevantTaxPayers() {
        return relevantTaxPayers;
    }

    /**
     * Sets the value of the relevantTaxPayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelevantTaxpayersType }
     *     
     */
    public void setRelevantTaxPayers(RelevantTaxpayersType value) {
        this.relevantTaxPayers = value;
    }

    /**
     * Gets the value of the intermediaries property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediariesType }
     *     
     */
    public IntermediariesType getIntermediaries() {
        return intermediaries;
    }

    /**
     * Sets the value of the intermediaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediariesType }
     *     
     */
    public void setIntermediaries(IntermediariesType value) {
        this.intermediaries = value;
    }

    /**
     * Gets the value of the affectedPersons property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedPersonsType }
     *     
     */
    public AffectedPersonsType getAffectedPersons() {
        return affectedPersons;
    }

    /**
     * Sets the value of the affectedPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedPersonsType }
     *     
     */
    public void setAffectedPersons(AffectedPersonsType value) {
        this.affectedPersons = value;
    }

    /**
     * Gets the value of the disclosureInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureInformationType }
     *     
     */
    public DisclosureInformationType getDisclosureInformation() {
        return disclosureInformation;
    }

    /**
     * Sets the value of the disclosureInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureInformationType }
     *     
     */
    public void setDisclosureInformation(DisclosureInformationType value) {
        this.disclosureInformation = value;
    }

    /**
     * Gets the value of the gdprUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGDPRUpdated() {
        return gdprUpdated;
    }

    /**
     * Sets the value of the gdprUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGDPRUpdated(Boolean value) {
        this.gdprUpdated = value;
    }

}
