//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisclosureVersion_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisclosureVersion_EnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DAC6INI"/&gt;
 *     &lt;enumeration value="DAC6UPD"/&gt;
 *     &lt;enumeration value="DAC6UNCH"/&gt;
 *     &lt;enumeration value="DAC6DEL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DisclosureVersion_EnumType")
@XmlEnum
public enum DisclosureVersionEnumType {


    /**
     * Initial version of a Disclosure
     * 
     */
    @XmlEnumValue("DAC6INI")
    DAC_6_INI("DAC6INI"),

    /**
     * New version of a Disclosure
     * 
     */
    @XmlEnumValue("DAC6UPD")
    DAC_6_UPD("DAC6UPD"),

    /**
     * Same version of the Disclosure
     * 
     */
    @XmlEnumValue("DAC6UNCH")
    DAC_6_UNCH("DAC6UNCH"),

    /**
     * Complete deletion of the Disclosure
     * 
     */
    @XmlEnumValue("DAC6DEL")
    DAC_6_DEL("DAC6DEL");
    private final String value;

    DisclosureVersionEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisclosureVersionEnumType fromValue(String v) {
        for (DisclosureVersionEnumType c: DisclosureVersionEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
