//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Hallmarks_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hallmarks_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ListHallmarks" type="{urn:eu:taxud:dac6:v1}ListHallmarks_Type"/&gt;
 *         &lt;element name="DAC6D1OtherInfo" type="{urn:eu:taxud:dac6:v1}StringMin1Max4000WithLang_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hallmarks_Type", propOrder = {
    "listHallmarks",
    "dac6D1OtherInfo"
})
public class HallmarksType {

    @XmlElement(name = "ListHallmarks", required = true)
    protected ListHallmarksType listHallmarks;
    @XmlElement(name = "DAC6D1OtherInfo")
    protected List<StringMin1Max4000WithLangType> dac6D1OtherInfo;

    /**
     * Gets the value of the listHallmarks property.
     * 
     * @return
     *     possible object is
     *     {@link ListHallmarksType }
     *     
     */
    public ListHallmarksType getListHallmarks() {
        return listHallmarks;
    }

    /**
     * Sets the value of the listHallmarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListHallmarksType }
     *     
     */
    public void setListHallmarks(ListHallmarksType value) {
        this.listHallmarks = value;
    }

    /**
     * Gets the value of the dac6D1OtherInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dac6D1OtherInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDAC6D1OtherInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringMin1Max4000WithLangType }
     * 
     * 
     */
    public List<StringMin1Max4000WithLangType> getDAC6D1OtherInfo() {
        if (dac6D1OtherInfo == null) {
            dac6D1OtherInfo = new ArrayList<StringMin1Max4000WithLangType>();
        }
        return this.dac6D1OtherInfo;
    }

}
