//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Intermediary_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Intermediary_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{urn:eu:taxud:dac6:v1}PersonOrOrganisation_Type"/&gt;
 *         &lt;element name="Capacity" type="{urn:eu:taxud:dac6:v1}IntermediaryCapacity_EnumType" minOccurs="0"/&gt;
 *         &lt;element name="NationalExemption" type="{urn:eu:taxud:dac6:v1}NationalExemption_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Intermediary_Type", propOrder = {
    "id",
    "capacity",
    "nationalExemption"
})
@XmlSeeAlso({
    Intermediary.class
})
public class IntermediaryType {

    @XmlElement(name = "ID", required = true)
    protected PersonOrOrganisationType id;
    @XmlElement(name = "Capacity")
    @XmlSchemaType(name = "string")
    protected IntermediaryCapacityEnumType capacity;
    @XmlElement(name = "NationalExemption")
    protected NationalExemptionType nationalExemption;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public PersonOrOrganisationType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public void setID(PersonOrOrganisationType value) {
        this.id = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediaryCapacityEnumType }
     *     
     */
    public IntermediaryCapacityEnumType getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediaryCapacityEnumType }
     *     
     */
    public void setCapacity(IntermediaryCapacityEnumType value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the nationalExemption property.
     * 
     * @return
     *     possible object is
     *     {@link NationalExemptionType }
     *     
     */
    public NationalExemptionType getNationalExemption() {
        return nationalExemption;
    }

    /**
     * Sets the value of the nationalExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalExemptionType }
     *     
     */
    public void setNationalExemption(NationalExemptionType value) {
        this.nationalExemption = value;
    }

}
