//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntermediaryCapacity_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IntermediaryCapacity_EnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DAC61101"/&gt;
 *     &lt;enumeration value="DAC61102"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IntermediaryCapacity_EnumType")
@XmlEnum
public enum IntermediaryCapacityEnumType {


    /**
     * Designer / Promoter / Implementation (managing/organizing/executing)
     * 
     */
    @XmlEnumValue("DAC61101")
    DAC_61101("DAC61101"),

    /**
     * Service Provider / Assistant
     * 
     */
    @XmlEnumValue("DAC61102")
    DAC_61102("DAC61102");
    private final String value;

    IntermediaryCapacityEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntermediaryCapacityEnumType fromValue(String v) {
        for (IntermediaryCapacityEnumType c: IntermediaryCapacityEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
