//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Liability_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Liability_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="IntermediaryDiscloser"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="IntermediaryNexus" type="{urn:eu:taxud:dac6:v1}IntermediaryNexus_EnumType" minOccurs="0"/&gt;
 *                   &lt;element name="Capacity" type="{urn:eu:taxud:dac6:v1}IntermediaryCapacity_EnumType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RelevantTaxpayerDiscloser"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RelevantTaxpayerNexus" type="{urn:eu:taxud:dac6:v1}RelevantTaxpayerNexus_EnumType" minOccurs="0"/&gt;
 *                   &lt;element name="Capacity" type="{urn:eu:taxud:dac6:v1}TaxpayerCapacity_EnumType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Liability_Type", propOrder = {
    "intermediaryDiscloser",
    "relevantTaxpayerDiscloser"
})
public class LiabilityType {

    @XmlElement(name = "IntermediaryDiscloser")
    protected LiabilityType.IntermediaryDiscloser intermediaryDiscloser;
    @XmlElement(name = "RelevantTaxpayerDiscloser")
    protected LiabilityType.RelevantTaxpayerDiscloser relevantTaxpayerDiscloser;

    /**
     * Gets the value of the intermediaryDiscloser property.
     * 
     * @return
     *     possible object is
     *     {@link LiabilityType.IntermediaryDiscloser }
     *     
     */
    public LiabilityType.IntermediaryDiscloser getIntermediaryDiscloser() {
        return intermediaryDiscloser;
    }

    /**
     * Sets the value of the intermediaryDiscloser property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiabilityType.IntermediaryDiscloser }
     *     
     */
    public void setIntermediaryDiscloser(LiabilityType.IntermediaryDiscloser value) {
        this.intermediaryDiscloser = value;
    }

    /**
     * Gets the value of the relevantTaxpayerDiscloser property.
     * 
     * @return
     *     possible object is
     *     {@link LiabilityType.RelevantTaxpayerDiscloser }
     *     
     */
    public LiabilityType.RelevantTaxpayerDiscloser getRelevantTaxpayerDiscloser() {
        return relevantTaxpayerDiscloser;
    }

    /**
     * Sets the value of the relevantTaxpayerDiscloser property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiabilityType.RelevantTaxpayerDiscloser }
     *     
     */
    public void setRelevantTaxpayerDiscloser(LiabilityType.RelevantTaxpayerDiscloser value) {
        this.relevantTaxpayerDiscloser = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="IntermediaryNexus" type="{urn:eu:taxud:dac6:v1}IntermediaryNexus_EnumType" minOccurs="0"/&gt;
     *         &lt;element name="Capacity" type="{urn:eu:taxud:dac6:v1}IntermediaryCapacity_EnumType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "intermediaryNexus",
        "capacity"
    })
    public static class IntermediaryDiscloser {

        @XmlElement(name = "IntermediaryNexus")
        @XmlSchemaType(name = "string")
        protected IntermediaryNexusEnumType intermediaryNexus;
        @XmlElement(name = "Capacity")
        @XmlSchemaType(name = "string")
        protected IntermediaryCapacityEnumType capacity;

        /**
         * Gets the value of the intermediaryNexus property.
         * 
         * @return
         *     possible object is
         *     {@link IntermediaryNexusEnumType }
         *     
         */
        public IntermediaryNexusEnumType getIntermediaryNexus() {
            return intermediaryNexus;
        }

        /**
         * Sets the value of the intermediaryNexus property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntermediaryNexusEnumType }
         *     
         */
        public void setIntermediaryNexus(IntermediaryNexusEnumType value) {
            this.intermediaryNexus = value;
        }

        /**
         * Gets the value of the capacity property.
         * 
         * @return
         *     possible object is
         *     {@link IntermediaryCapacityEnumType }
         *     
         */
        public IntermediaryCapacityEnumType getCapacity() {
            return capacity;
        }

        /**
         * Sets the value of the capacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntermediaryCapacityEnumType }
         *     
         */
        public void setCapacity(IntermediaryCapacityEnumType value) {
            this.capacity = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RelevantTaxpayerNexus" type="{urn:eu:taxud:dac6:v1}RelevantTaxpayerNexus_EnumType" minOccurs="0"/&gt;
     *         &lt;element name="Capacity" type="{urn:eu:taxud:dac6:v1}TaxpayerCapacity_EnumType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relevantTaxpayerNexus",
        "capacity"
    })
    public static class RelevantTaxpayerDiscloser {

        @XmlElement(name = "RelevantTaxpayerNexus")
        @XmlSchemaType(name = "string")
        protected RelevantTaxpayerNexusEnumType relevantTaxpayerNexus;
        @XmlElement(name = "Capacity")
        @XmlSchemaType(name = "string")
        protected TaxpayerCapacityEnumType capacity;

        /**
         * Gets the value of the relevantTaxpayerNexus property.
         * 
         * @return
         *     possible object is
         *     {@link RelevantTaxpayerNexusEnumType }
         *     
         */
        public RelevantTaxpayerNexusEnumType getRelevantTaxpayerNexus() {
            return relevantTaxpayerNexus;
        }

        /**
         * Sets the value of the relevantTaxpayerNexus property.
         * 
         * @param value
         *     allowed object is
         *     {@link RelevantTaxpayerNexusEnumType }
         *     
         */
        public void setRelevantTaxpayerNexus(RelevantTaxpayerNexusEnumType value) {
            this.relevantTaxpayerNexus = value;
        }

        /**
         * Gets the value of the capacity property.
         * 
         * @return
         *     possible object is
         *     {@link TaxpayerCapacityEnumType }
         *     
         */
        public TaxpayerCapacityEnumType getCapacity() {
            return capacity;
        }

        /**
         * Sets the value of the capacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaxpayerCapacityEnumType }
         *     
         */
        public void setCapacity(TaxpayerCapacityEnumType value) {
            this.capacity = value;
        }

    }

}
