//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NationalExemption_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NationalExemption_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Exemption" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CountryExemptions" type="{urn:eu:taxud:dac6:v1}CountryExemptions_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NationalExemption_Type", propOrder = {
    "exemption",
    "countryExemptions"
})
public class NationalExemptionType {

    @XmlElement(name = "Exemption")
    protected boolean exemption;
    @XmlElement(name = "CountryExemptions")
    protected CountryExemptionsType countryExemptions;

    /**
     * Gets the value of the exemption property.
     * 
     */
    public boolean isExemption() {
        return exemption;
    }

    /**
     * Sets the value of the exemption property.
     * 
     */
    public void setExemption(boolean value) {
        this.exemption = value;
    }

    /**
     * Gets the value of the countryExemptions property.
     * 
     * @return
     *     possible object is
     *     {@link CountryExemptionsType }
     *     
     */
    public CountryExemptionsType getCountryExemptions() {
        return countryExemptions;
    }

    /**
     * Sets the value of the countryExemptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryExemptionsType }
     *     
     */
    public void setCountryExemptions(CountryExemptionsType value) {
        this.countryExemptions = value;
    }

}
