//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dac6.convert.dac6.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dac6.convert.dac6.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrangementChartType }
     * 
     */
    public ArrangementChartType createArrangementChartType() {
        return new ArrangementChartType();
    }

    /**
     * Create an instance of {@link LiabilityType }
     * 
     */
    public LiabilityType createLiabilityType() {
        return new LiabilityType();
    }

    /**
     * Create an instance of {@link DAC6Arrangement }
     * 
     */
    public DAC6Arrangement createDAC6Arrangement() {
        return new DAC6Arrangement();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link DAC6DisclosureType }
     * 
     */
    public DAC6DisclosureType createDAC6DisclosureType() {
        return new DAC6DisclosureType();
    }

    /**
     * Create an instance of {@link StringMin1Max4000WithLangType }
     * 
     */
    public StringMin1Max4000WithLangType createStringMin1Max4000WithLangType() {
        return new StringMin1Max4000WithLangType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Discloser }
     * 
     */
    public Discloser createDiscloser() {
        return new Discloser();
    }

    /**
     * Create an instance of {@link TaxPayerType }
     * 
     */
    public TaxPayerType createTaxPayerType() {
        return new TaxPayerType();
    }

    /**
     * Create an instance of {@link AssociatedEnterprisesType }
     * 
     */
    public AssociatedEnterprisesType createAssociatedEnterprisesType() {
        return new AssociatedEnterprisesType();
    }

    /**
     * Create an instance of {@link AssociatedEnterpriseType }
     * 
     */
    public AssociatedEnterpriseType createAssociatedEnterpriseType() {
        return new AssociatedEnterpriseType();
    }

    /**
     * Create an instance of {@link AffectedPersonType }
     * 
     */
    public AffectedPersonType createAffectedPersonType() {
        return new AffectedPersonType();
    }

    /**
     * Create an instance of {@link NameOrganisationType }
     * 
     */
    public NameOrganisationType createNameOrganisationType() {
        return new NameOrganisationType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link TINType }
     * 
     */
    public TINType createTINType() {
        return new TINType();
    }

    /**
     * Create an instance of {@link IntermediaryType }
     * 
     */
    public IntermediaryType createIntermediaryType() {
        return new IntermediaryType();
    }

    /**
     * Create an instance of {@link NationalExemptionType }
     * 
     */
    public NationalExemptionType createNationalExemptionType() {
        return new NationalExemptionType();
    }

    /**
     * Create an instance of {@link CountryExemptionsType }
     * 
     */
    public CountryExemptionsType createCountryExemptionsType() {
        return new CountryExemptionsType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link NamePersonType }
     * 
     */
    public NamePersonType createNamePersonType() {
        return new NamePersonType();
    }

    /**
     * Create an instance of {@link PersonOrOrganisationType }
     * 
     */
    public PersonOrOrganisationType createPersonOrOrganisationType() {
        return new PersonOrOrganisationType();
    }

    /**
     * Create an instance of {@link ListHallmarksType }
     * 
     */
    public ListHallmarksType createListHallmarksType() {
        return new ListHallmarksType();
    }

    /**
     * Create an instance of {@link DisclosingType }
     * 
     */
    public DisclosingType createDisclosingType() {
        return new DisclosingType();
    }

    /**
     * Create an instance of {@link TaxPayer }
     * 
     */
    public TaxPayer createTaxPayer() {
        return new TaxPayer();
    }

    /**
     * Create an instance of {@link Intermediary }
     * 
     */
    public Intermediary createIntermediary() {
        return new Intermediary();
    }

    /**
     * Create an instance of {@link DisclosureInformationType }
     * 
     */
    public DisclosureInformationType createDisclosureInformationType() {
        return new DisclosureInformationType();
    }

    /**
     * Create an instance of {@link HallmarksType }
     * 
     */
    public HallmarksType createHallmarksType() {
        return new HallmarksType();
    }

    /**
     * Create an instance of {@link IntermediariesType }
     * 
     */
    public IntermediariesType createIntermediariesType() {
        return new IntermediariesType();
    }

    /**
     * Create an instance of {@link AffectedPersonsType }
     * 
     */
    public AffectedPersonsType createAffectedPersonsType() {
        return new AffectedPersonsType();
    }

    /**
     * Create an instance of {@link ConcernedMSsType }
     * 
     */
    public ConcernedMSsType createConcernedMSsType() {
        return new ConcernedMSsType();
    }

    /**
     * Create an instance of {@link RelevantTaxpayersType }
     * 
     */
    public RelevantTaxpayersType createRelevantTaxpayersType() {
        return new RelevantTaxpayersType();
    }

    /**
     * Create an instance of {@link ArrangementChartType.ListChilds }
     * 
     */
    public ArrangementChartType.ListChilds createArrangementChartTypeListChilds() {
        return new ArrangementChartType.ListChilds();
    }

    /**
     * Create an instance of {@link LiabilityType.IntermediaryDiscloser }
     * 
     */
    public LiabilityType.IntermediaryDiscloser createLiabilityTypeIntermediaryDiscloser() {
        return new LiabilityType.IntermediaryDiscloser();
    }

    /**
     * Create an instance of {@link LiabilityType.RelevantTaxpayerDiscloser }
     * 
     */
    public LiabilityType.RelevantTaxpayerDiscloser createLiabilityTypeRelevantTaxpayerDiscloser() {
        return new LiabilityType.RelevantTaxpayerDiscloser();
    }

}
