//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxpayerCapacity_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaxpayerCapacity_EnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DAC61104"/&gt;
 *     &lt;enumeration value="DAC61105"/&gt;
 *     &lt;enumeration value="DAC61106"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TaxpayerCapacity_EnumType")
@XmlEnum
public enum TaxpayerCapacityEnumType {


    /**
     * Professional secrecy of intermediary
     * 
     */
    @XmlEnumValue("DAC61104")
    DAC_61104("DAC61104"),

    /**
     * Intermediary in non-EU country
     * 
     */
    @XmlEnumValue("DAC61105")
    DAC_61105("DAC61105"),

    /**
     * In-house Arrangement
     * 
     */
    @XmlEnumValue("DAC61106")
    DAC_61106("DAC61106");
    private final String value;

    TaxpayerCapacityEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TaxpayerCapacityEnumType fromValue(String v) {
        for (TaxpayerCapacityEnumType c: TaxpayerCapacityEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
