//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 09:09:38 AM CET 
//


package com.dac6.convert.dac6.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TaxPayer_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxPayer_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{urn:eu:taxud:dac6:v1}PersonOrOrganisation_Type"/&gt;
 *         &lt;element name="TaxpayerImplementingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="AssociatedEnterprises" type="{urn:eu:taxud:dac6:v1}AssociatedEnterprises_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxPayer_Type", propOrder = {
    "id",
    "taxpayerImplementingDate",
    "associatedEnterprises"
})
@XmlSeeAlso({
    TaxPayer.class
})
public class TaxPayerType {

    @XmlElement(name = "ID", required = true)
    protected PersonOrOrganisationType id;
    @XmlElement(name = "TaxpayerImplementingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar taxpayerImplementingDate;
    @XmlElement(name = "AssociatedEnterprises")
    protected AssociatedEnterprisesType associatedEnterprises;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public PersonOrOrganisationType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganisationType }
     *     
     */
    public void setID(PersonOrOrganisationType value) {
        this.id = value;
    }

    /**
     * Gets the value of the taxpayerImplementingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxpayerImplementingDate() {
        return taxpayerImplementingDate;
    }

    /**
     * Sets the value of the taxpayerImplementingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaxpayerImplementingDate(XMLGregorianCalendar value) {
        this.taxpayerImplementingDate = value;
    }

    /**
     * Gets the value of the associatedEnterprises property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedEnterprisesType }
     *     
     */
    public AssociatedEnterprisesType getAssociatedEnterprises() {
        return associatedEnterprises;
    }

    /**
     * Sets the value of the associatedEnterprises property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedEnterprisesType }
     *     
     */
    public void setAssociatedEnterprises(AssociatedEnterprisesType value) {
        this.associatedEnterprises = value;
    }

}
